presets = {
    "complex-analysis-uark": "\\documentclass[12pt,oneside]{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage{scsnowman, lmodern, amsmath, amsthm, amsfonts,amssymb, dsfont, wasysym, mathdots,qtree}\n\\makeatletter\n\\@ifpackagelater{sansmathfonts}{2019/03/31}\n{\\usepackage[I]{sansmathfonts}}\n{\\usepackage{sansmathfonts}}\n\\makeatother \\let \\rmdefault \\sfdefault\n\\usepackage[paperwidth=148mm, paperheight=182.4mm, vmargin=1cm]{geometry}\n\\let \\thepage \\relax\n\\pagestyle{empty}\n\\usepackage{setspace} \\doublespacing\n\\usepackage{enumitem}\n\\setenumerate[1]{label=(\\alph*)}\n\\setenumerate[2]{label=(\\roman*)}\n\\setlist{\n  listparindent=\\parindent,\n  parsep=0pt,\n}\n\\newcommand{\\problem}[2]{\\par\n   {\\onehalfspacing\n  \\setenumerate[1]{label=(\\alph*),nolistsep}\n  \\setenumerate[2]{label=(\\roman*),nolistsep}\n  \\noindent\\textbf{Problem #1}\n  {\\rmfamily #2\\par\\medskip}} \\sffamily}\n\\newcommand{\\re}{\\operatorname{Re}}\\newcommand{\im}{\\operatorname{Im}}\\newcommand{\\spn}{\\operatorname{span}}\\newcommand{\\tr}{\\operatorname{tr}}\\newcommand{\\Res}{\\operatorname{Res}}\n\\newcommand{\\ord}{\\operatorname{ord}}\n",
    "fun-math": "\\documentclass[10pt,reqno]{amsart}\n\\usepackage{eucal,fullpage,times,amsmath,amsthm,amssymb,mathrsfs,stmaryrd,color,accents,tipa,relsize,wasysym,dsfont,url,tikz,tikz-cd,qtree,mathdots}\n\\usepackage[all]{xy}\n\\usepackage[ margin=2cm]{geometry}\n\\usepackage[colorlinks=false,pagebackref,hyperindex]{hyperref}\n\\usetikzlibrary{arrows,matrix}\n\\hypersetup{colorlinks,citecolor=violet,linkcolor=violet,urlcolor=blue}\n\\newtheoremstyle{custom}{}{}{}{}{}{.}{ }{\\thmname{}\\thmnumber{}\\thmnote{\\bfseries #3}}\n\\newtheoremstyle{Theorem }{}{}{\itshape}{}{}{.}{ }{\\thmname{\\bfseries #1}\\thmnumber{\;\\bfseries #2}\\thmnote{\;(\\bfseries #3)}}\n\\theoremstyle{Theorem}\n\\newtheorem{thm}{Theorem}[section]\n\\newtheorem{cor}[thm]{Corollary}\n\\newtheorem{lem}[thm]{Lemma}\n\\newtheorem{prop}{Proposition}[section]\n\\theoremstyle{definition}\n\\newtheorem{dff}[thm]{Definition}\n\\newtheorem{xmp}[thm]{Example}\n\\newtheorem{rmk}[thm]{Remark}\n\\newtheorem{prob}[thm]{Problem}\n\\newtheorem{conj}[thm]{Conjecture}\n\\newenvironment{solution}{\paragraph{\\textit{Solution:}}}{\hfill$\\smiley$\\\\}\n\\newcommand{\\spn}{\\operatorname{span}}\\newcommand{\im}{\\operatorname{Im}}\\newcommand{\\tr}{\\operatorname{tr}}\\newcommand{\\Aut}{\\operatorname{Aut}}\n\\newcommand{\\ord}{\\operatorname{ord}}\n\\newcommand{\\Syl}{\\operatorname{Syl}}"
}
envreplacements = {
    "⍞": "center",
    "Ⓣ": "thm",
    "ⓣ": "tikzcd", #will have issues
    "Ⓘ": "itemize",
    "ⓔ": "enumerate",
    "Ⓒ": "cor",
    "Ⓛ": "lem",
    "Ⓟ": "prop",
    "Ⓓ": "dff",
    "Ⓔ": "xmp",
    "Ⓡ": "rmk",
    "ⓟ": "prob",
    "ⓒ": "conj",
    "Ⓢ": "solution",
    "🅟": "proof"
}
mathenvreplacements = {
    "Ⓐ": "align*",
    "ⓐ": "align",
    "Ⓜ": "alignat*",
    "ⓜ": "alignat",
}
englishreplacements = {
    "≖": "is conformally equivalent to",
    "∀": "for all",
    "∃": "there is",
    "∧": "and",
    "∨": "or",
    "𝅘𝅥": "note",
    "𝅘𝅥𝅰": "this is left as an exercise for the reader",
    "✣": "such that",
    "󲘆": "which was what we wanted", #update
    "󲘨": "with respect to", #update
    "󲘩": "want to show", #update
    "󲘪": "want to find", #update
    "󲘻": "without loss of generality", #update
    "⎉": "let",
    "⎊": "define",
    "ᔲ": "suppose", #make sequence
    "🝤": "by induction",
    "↘": "on",
    "¿": "if",
    "¡": "otherwise",
    "``": "else",
    "∵": "because",
    "∴": "thus",
    "↣": "then",
    "⍟": "the diagram",
    "⚇": "commutes",
    "Æ": "almost everywhere", #add sequence
    "󰘡": "bounded below", #add sequence
    "󰡏": "bounded", #add sequence
    "󰘣": "bounded above", #add sequence
    "⍇": "has",
    "☒": "does not have", #add sequence
    "󰇚": "with",
    "󱂰": "without",
    "󰮧": "property",
    "󱏗": "without property",
    "󱅙": "the property that",
    "󱏖": "the additional property that",
    "󰶀": "property $1$",
    "󰶁": "property $2$",
    "󰶂": "property $3$",
    "󰶃": "property $A$",
    "󰶄": "property $B$",
    "⎔": "of",
    "``": "a bijection",
    "󰚥": "a surjection",
    "󰎑": "an injection",
    "󰘨": "a matrix", #add sequence
    "󱁕": "a tree",
    "󰡷": "a graph",
    "󱘎": "a family",
    "": "a derangement",
    "󰬀": "a set",
    "󱇙": "a partition",
    "󰑇": "a relation", #fix maybe rhek
    "󰫰": "a category",
    "󱨹": "a functor",
    "": "a morphism",
    "▢": "an object",
    "": "a point",
    "󰕞": "a line",
    "": "a node",
    "󰝊": "an edge",
    "󰬁": "a topology",
    "󰷔": "a neighborhood",
    "󱁐": "a space",
    "": "a manifold",
    "``": "an atlas",
    "``": "a chart",
    "󰡱": "a polynomial",
    "ᾇ": "a scalar",
    "": "a vector",
    "󰫺": "a module",
    "󰗴": "a tensor",
    "󰨥": "a basis",
    "󰫴": "a group",
    "󰫿": "a ring",
    "": "a topological space",
    "󰫳": "a field",
    "󰬃": "a vector space",
    "󱗿": "a lattice",
    "󰫱": "a domain",
    "␌": "a form",
    "󱧡": "an ideal",
    "󰫶": "an ID",
    "󰬂": "a UFD",
    "󰫽": "a PID",
    "󰫲": "an ED",
    "``": "an ICD",
    "``": "a GCDD",
    "": "a DVR",
    "󰊕": "a function",
    "``": "a semiring",
    "``": "a magma",
    "``": "a monoid",
    "``": "a semigroup",
    "``": "a quasigroup",
    "➰": "a loop",
    "󰫮": "an algebra",
    "󰊰": "a $\\sigma$-algebra",
    "󰉷": "an isomorphism",
    "󰠩": "a homomorphism",
    "󰑭": "a measure",
    "󰉽": "a path",
    "󰊄": "a transformation",
    "": "an example",
    "󰿨": "a chain",
    "": "an element",
    "󰣰": "a metric",
    "󰍒": "a metric space",
    "✓": "holds",
    "⚙": "generate by",
    "󰍉": "find",
    "": "fix",
    "⎋": "a primitive root mod", #add sequence proot
    "``": "a representation",
    "⊯": "is not", #add sequence i/s (add in for ∈)
    "⮎": "acts on", #add sequence
    "⮌": "is acted on by",
    "⪟": "is isomorphic to a subgroup of", #add sequence eqi<
    "⪠": "contains a subgroup isomorphic to" #add sequence eqi>
}
#⫢ is special because conjugation and maybe ⍇ and maybe ⎔
#ideas to add: 󰭃󰉤󰉽󰔆󱎤󱎥󱎦󰜕󰙱󰏣󰘧󰬰󱃠󱈚󱘗󱔏󱣩󰞦󱙮󰨈󰶅󰶆󱎱󱏕󰳋󱍢󱐚
#new characters list: 󱔏󰉤󰙱󰬰󱈚󰠩󰉷󰔆󱎥󰭃󰘧
# 󰤱 add words: also
replacements = {
    # "🯆": "\\begin{document}",
    # "🯈": "\\section",
    # "🯇": "\\newpage",
    # "🯅": "\\maketitle",
    # "𖧀": "\\end{document}",
    # "🖻": "🗋[10pt,reqno]{amsart}\n",
    # "🗋": "\\documentclass",
    # "📦": "𝌤{eucal,fullpage,times,amsmath,amsthm,amssymb,mathrsfs,stmaryrd,color,accents,tipa,relsize,wasysym,dsfont,url,tikz,tikz-cd}\n𝌤[all]{xy}\n𝌤[ margin=2cm]{geometry}\n𝌤[colorlinks=false,pagebackref,hyperindex]{hyperref}\n\\usetikzlibrary{arrows,matrix}\n",
    # "𝌤": "\\usepackage",
    # "🔗": "🖇{colorlinks,citecolor=violet,linkcolor=violet,urlcolor=blue}\n",
    # "🖇": "\\hypersetup",
    # "❔": "\\newtheoremstyle{custom}{}{}{}{}{}{.}{ }{\\thmname{}\\thmnumber{}\\thmnote{\\bfseries #3}}\n\\newtheoremstyle{Theorem }{}{}{\itshape}{}{}{.}{ }{\\thmname{\\bfseries #1}\\thmnumber{\;\\bfseries #2}\\thmnote{\;(\\bfseries #3)}}\n\\theoremstyle{Theorem}\n\\newtheorem{thm}{Theorem}[section]\n\\newtheorem{cor}[thm]{Corollary}\n\\newtheorem{lem}[thm]{Lemma}\n\\newtheorem{prop}{Proposition}[section]\n\\theoremstyle{definition}\n\\newtheorem{dff}[thm]{Definition}\n\\newtheorem{xmp}[thm]{Example}\n\\newtheorem{rmk}[thm]{Remark}\n\\newtheorem{prob}[thm]{Problem}\n\\newtheorem{conj}[thm]{Conjecture}\n\\newenvironment{solution}{\paragraph{\\textit{Solution:}}}{\hfill$☺$\\\\}\n",
    "⩩": "\\nonumber",
    # "⊢": "\\item ",
    "𝟘": "\\mathbf{0}",
    "𝟙": "\\mathbf{1}",
    "𝟚": "\\mathbf{2}",
    "𝟛": "\\mathbf{3}",
    "𝟜": "\\mathbf{4}",
    "𝟝": "\\mathbf{5}",
    "𝟞": "\\mathbf{6}",
    "𝟟": "\\mathbf{7}",
    "𝟠": "\\mathbf{8}",
    "𝟡": "\\mathbf{9}",
    "ℚ": "\\mathds{Q}",
    "𝕎": "\\mathds{W}",
    "𝔼": "\\mathds{E}",
    "ℝ": "\\mathds{R}",
    "𝕋": "\\mathds{T}",
    "𝕐": "\\mathds{Y}",
    "𝕌": "\\mathds{U}",
    "𝕀": "\\mathds{I}",
    "𝕆": "\\mathds{O}",
    "ℙ": "\\mathds{P}",
    "𝔸": "\\mathds{A}",
    "𝕊": "\\mathds{S}",
    "𝔻": "\\mathds{D}",
    "𝔽": "\\mathds{F}",
    "𝔾": "\\mathds{G}",
    "ℍ": "\\mathds{H}",
    "𝕁": "\\mathds{J}",
    "𝕂": "\\mathds{K}",
    "𝕃": "\\mathds{L}",
    "ℤ": "\\mathds{Z}",
    "𝕏": "\\mathds{X}",
    "ℂ": "\\mathds{C}",
    "𝕍": "\\mathds{V}",
    "𝔹": "\\mathds{B}",
    "ℕ": "\\mathds{N}",
    "𝕄": "\\mathds{M}",
    "𝕢": "\\mathds{q}",
    "𝕨": "\\mathds{w}",
    "𝕖": "\\mathds{e}",
    "𝕣": "\\mathds{r}",
    "𝕥": "\\mathds{t}",
    "𝕪": "\\mathds{y}",
    "𝕦": "\\mathds{u}",
    "𝕚": "\\mathds{i}",
    "𝕠": "\\mathds{o}",
    "𝕡": "\\mathds{p}",
    "𝕒": "\\mathds{a}",
    "𝕤": "\\mathds{s}",
    "𝕕": "\\mathds{d}",
    "𝕗": "\\mathds{f}",
    "𝕘": "\\mathds{g}",
    "𝕙": "\\mathds{h}",
    "𝕛": "\\mathds{j}",
    "𝕜": "\\mathds{k}",
    "𝕝": "\\mathds{l}",
    "𝕫": "\\mathds{z}",
    "𝕩": "\\mathds{x}",
    "𝕔": "\\mathds{c}",
    "𝕧": "\\mathds{v}",
    "𝕓": "\\mathds{b}",
    "𝕟": "\\mathds{n}",
    "𝕞": "\\mathds{m}",
    "𝔔": "\\mathfrak{Q}",
    "𝔚": "\\mathfrak{W}",
    "𝔈": "\\mathfrak{E}",
    "ℜ": "\\mathfrak{R}",
    "𝔗": "\\mathfrak{T}",
    "𝔜": "\\mathfrak{Y}",
    "𝔘": "\\mathfrak{U}",
    "ℑ": "\\mathfrak{I}",
    "𝔒": "\\mathfrak{O}",
    "𝔓": "\\mathfrak{P}",
    "𝔄": "\\mathfrak{A}",
    "𝔖": "\\mathfrak{S}",
    "𝔇": "\\mathfrak{D}",
    "𝔉": "\\mathfrak{F}",
    "𝔊": "\\mathfrak{G}",
    "ℌ": "\\mathfrak{H}",
    "𝔍": "\\mathfrak{J}",
    "𝔎": "\\mathfrak{K}",
    "𝔏": "\\mathfrak{L}",
    "ℨ": "\\mathfrak{Z}",
    "𝔛": "\\mathfrak{X}",
    "ℭ": "\\mathfrak{C}",
    "𝔙": "\\mathfrak{V}",
    "𝔅": "\\mathfrak{B}",
    "𝔑": "\\mathfrak{N}",
    "𝔐": "\\mathfrak{M}",
    "𝔮": "\\mathfrak{q}",
    "𝔴": "\\mathfrak{w}",
    "𝔢": "\\mathfrak{e}",
    "𝔯": "\\mathfrak{r}",
    "𝔱": "\\mathfrak{t}",
    "𝔶": "\\mathfrak{y}",
    "𝔲": "\\mathfrak{u}",
    "𝔦": "\\mathfrak{i}",
    "𝔬": "\\mathfrak{o}",
    "𝔭": "\\mathfrak{p}",
    "𝔞": "\\mathfrak{a}",
    "𝔰": "\\mathfrak{s}",
    "𝔡": "\\mathfrak{d}",
    "𝔣": "\\mathfrak{f}",
    "𝔤": "\\mathfrak{g}",
    "𝔥": "\\mathfrak{h}",
    "𝔧": "\\mathfrak{j}",
    "𝔨": "\\mathfrak{k}",
    "𝔩": "\\mathfrak{l}",
    "𝔷": "\\mathfrak{z}",
    "𝔵": "\\mathfrak{x}",
    "𝔠": "\\mathfrak{c}",
    "𝔳": "\\mathfrak{v}",
    "𝔟": "\\mathfrak{b}",
    "𝔫": "\\mathfrak{n}",
    "𝔪": "\\mathfrak{m}",
    "𝓠": "\\mathcal{Q}",
    "𝓦": "\\mathcal{W}",
    "𝓔": "\\mathcal{E}",
    "𝓡": "\\mathcal{R}",
    "𝓣": "\\mathcal{T}",
    "𝓨": "\\mathcal{Y}",
    "𝓤": "\\mathcal{U}",
    "𝓘": "\\mathcal{I}",
    "𝓞": "\\mathcal{O}",
    "𝓟": "\\mathcal{P}",
    "𝓐": "\\mathcal{A}",
    "𝓢": "\\mathcal{S}",
    "𝓓": "\\mathcal{D}",
    "𝓕": "\\mathcal{F}",
    "𝓖": "\\mathcal{G}",
    "𝓗": "\\mathcal{H}",
    "𝓙": "\\mathcal{J}",
    "𝓚": "\\mathcal{K}",
    "𝓛": "\\mathcal{L}",
    "𝓩": "\\mathcal{Z}",
    "𝓧": "\\mathcal{X}",
    "𝓒": "\\mathcal{C}",
    "𝓥": "\\mathcal{V}",
    "𝓑": "\\mathcal{B}",
    "𝓝": "\\mathcal{N}",
    "𝓜": "\\mathcal{M}",
    "𝓺": "\\mathcal{q}",
    "𝔀": "\\mathcal{w}",
    "𝓮": "\\mathcal{e}",
    "𝓻": "\\mathcal{r}",
    "𝓽": "\\mathcal{t}",
    "𝔂": "\\mathcal{y}",
    "𝓾": "\\mathcal{u}",
    "𝓲": "i",
    "𝓸": "\\mathcal{o}",
    "𝓹": "\\mathcal{p}",
    "𝓪": "\\mathcal{a}",
    "𝓼": "\\mathcal{s}",
    "𝓭": "\\mathcal{d}",
    "𝓯": "\\mathcal{f}",
    "𝓰": "\\mathcal{g}",
    "𝓱": "\\mathcal{h}",
    "𝓳": "\\mathcal{j}",
    "𝓴": "\\mathcal{k}",
    "𝓵": "\\ell",
    "𝔃": "\\mathcal{z}",
    "𝔁": "\\mathcal{x}",
    "𝓬": "\\mathcal{c}",
    "𝓿": "\\mathcal{v}",
    "𝓫": "\\mathcal{b}",
    "𝓷": "\\mathcal{n}",
    "𝓶": "\\mathcal{m}",
    "ɑ": "\\alpha ",
    "α": "\\alpha ",
    "β": "\\beta ",
    "γ": "\\gamma ",
    "Γ": "\\Gamma ",
    "δ": "\\delta ",
    "Δ": "\\Delta ",
    "ε": "\\varepsilon ",
    "ζ": "\\zeta ",
    "η": "\\eta ",
    "θ": "\\theta ",
    "Θ": "\\Theta ",
    "ι": "\\iota ",
    "κ": "\\kappa ",
    "λ": "\\lambda ",
    "Λ": "\\Lambda ",
    "μ": "\\mu ",
    "ν": "\\nu ",
    "ξ": "\\xi ",
    "Ξ": "\\Xi ",
    "ο": "\\omicron ",
    "π": "\\pi ",
    "𝜋": "\\pi ",
    "Π": "\\prod ",
    "ρ": "\\rho ",
    "σ": "\\sigma ",
    "Σ": "\\sum ",
    "τ": "\\tau ",
    "υ": "\\upsilon ",
    "φ": "\\varphi ",
    "Φ": "\\Phi ",
    "χ": "\\chi ",
    "ψ": "\\psi ",
    "Ψ": "\\Psi ",
    "ω": "\\omega ",
    "Ω": "\\Omega ",
    "⨆": "\\coprod ",
    "½": "\\frac{1}{2}",
    "⅓": "\\frac{1}{3}",
    "¼": "\\frac{1}{4}",
    "⅕": "\\frac{1}{5}",
    "⅙": "\\frac{1}{6}",
    "⅐": "\\frac{1}{7}",
    "⅛": "\\frac{1}{8}",
    "⅑": "\\frac{1}{9}",
    "⅒": "\\frac{1}{10}",
    "↉": "\\frac{0}{3}",
    "⅔": "\\frac{2}{3}",
    "⅖": "\\frac{2}{5}",
    "¾": "\\frac{3}{4}",
    "⅗": "\\frac{3}{5}",
    "⅜": "\\frac{3}{8}",
    "⅘": "\\frac{4}{5}",
    "⅚": "\\frac{5}{6}",
    "⅝": "\\frac{5}{8}",
    "⅞": "\\frac{7}{8}",
    "﹕": ":",
    "󱴖": "\\in ",
    "₋": "-",
    "₊": "+",
    "󱼫": "/",
    "₌": "=",
    "󱽔": "_i", #to change
    "󱽕": "^i", #to change
    "󱽒": "_n", #to change
    "󱽓": "^n", #to change
    "󱽘": "_k", #to change
    "󱽙": "^k", #to change
    "₀": "0",
    "󱽎": "_0", #to change
    "󱽏": "^0", #to change
    "₁": "1",
    "󱽐": "_1", #to change
    "󱽑": "^1", #to change
    "󱽍": "\\text{¶}",
    "󱳲": "\\neq ",
    "󱼫": "/",
    "󱼦": "|",
    "₂": "2",
    "₃": "3",
    "₄": "4",
    "₅": "5",
    "₆": "6",
    "₇": "7",
    "₈": "8",
    "₉": "9",
    "󱼅": "\\frac{0}{3}",
    "󱻺": "\\frac{1}{2}",
    "󱻻": "\\frac{1}{3}",
    "󱻼": "\\frac{1}{4}",
    "󱻽": "\\frac{1}{5}",
    "󱻾": "\\frac{1}{6}",
    "󱻿": "\\frac{1}{7}",
    "󱼀": "\\frac{1}{8}",
    "󱼁": "\\frac{1}{9}",
    "󱼂": "\\frac{1}{10}",
    "󱼃": "\\frac{2}{3}",
    "󱼄": "\\frac{2}{5}",
    "󱼆": "\\frac{3}{4}",
    "󱼇": "\\frac{3}{5}",
    "󱼈": "\\frac{3}{8}",
    "󱼉": "\\frac{4}{5}",
    "󱼊": "\\frac{5}{6}",
    "󱼋": "\\frac{5}{8}",
    "󱼌": "\\frac{7}{8}",
    "ₐ": "a",
    "": "b",
    "": "c",
    "": "d",
    "ₑ": "e",
    "": "f",
    "": "g",
    "ₕ": "h",
    "ᵢ": "i",
    "ⱼ": "j",
    "ₖ": "k",
    "ₗ": "l",
    "ₘ": "m",
    "ₙ": "n",
    "ₒ": "o",
    "ₚ": "p",
    "": "q",
    "ᵣ": "r",
    "ₛ": "s",
    "ₜ": "t",
    "ᵤ": "u",
    "ᵥ": "v",
    "": "w",
    "ₓ": "x",
    "": "y",
    "": "z",
    "󰂓": "A",
    "󰂔": "B",
    "󰂕": "C",
    "󰂖": "D",
    "󰂗": "E",
    "󰂘": "F",
    "󰂙": "G",
    "󰂚": "H",
    "󰂛": "I",
    "󰂜": "J",
    "󰂝": "K",
    "󰂞": "L",
    "󰂟": "M",
    "󰂠": "N",
    "󰂡": "O",
    "󰂢": "P",
    "󰂣": "Q",
    "󰂤": "R",
    "󰂥": "S",
    "󰂦": "T",
    "󰂧": "U",
    "󰂨": "V",
    "󰂩": "W",
    "󰂪": "X",
    "󰂫": "Y",
    "󰂬": "Z",
    "󱫲": "\\mathds{0}",
    "󱫳": "\\mathds{1}",
    "󱫴": "\\mathds{2}",
    "󱫵": "\\mathds{3}",
    "󱫶": "\\mathds{4}",
    "󱫷": "\\mathds{5}",
    "󱫸": "\\mathds{6}",
    "󱫹": "\\mathds{7}",
    "󱫺": "\\mathds{8}",
    "󱫻": "\\mathds{9}",
    "󱬖": "\\mathds{a}",
    "󱬗": "\\mathds{b}",
    "󱬘": "\\mathds{c}",
    "󱬙": "\\mathds{d}",
    "󱬚": "\\mathds{e}",
    "󱬛": "\\mathds{f}",
    "󱬜": "\\mathds{g}",
    "󱬝": "\\mathds{h}",
    "󱬞": "\\mathds{i}",
    "󱬟": "\\mathds{j}",
    "󱬠": "\\mathds{k}",
    "󱬡": "\\mathds{l}",
    "󱬢": "\\mathds{m}",
    "󱬣": "\\mathds{n}",
    "󱬤": "\\mathds{o}",
    "󱬥": "\\mathds{p}",
    "󱬦": "\\mathds{q}",
    "󱬧": "\\mathds{r}",
    "󱬨": "\\mathds{s}",
    "󱬩": "\\mathds{t}",
    "󱬪": "\\mathds{u}",
    "󱬫": "\\mathds{v}",
    "󱬬": "\\mathds{w}",
    "󱬭": "\\mathds{x}",
    "󱬮": "\\mathds{y}",
    "󱬯": "\\mathds{z}",
    "󱫼": "\\mathds{A}",
    "󱫽": "\\mathds{B}",
    "󱫾": "\\mathds{C}",
    "󱫿": "\\mathds{D}",
    "󱬀": "\\mathds{E}",
    "󱬁": "\\mathds{F}",
    "󱬂": "\\mathds{G}",
    "󱬃": "\\mathds{H}",
    "󱬄": "\\mathds{I}",
    "󱬅": "\\mathds{J}",
    "󱬆": "\\mathds{K}",
    "󱬇": "\\mathds{L}",
    "󱬈": "\\mathds{M}",
    "󱬉": "\\mathds{N}",
    "󱬊": "\\mathds{O}",
    "󱬋": "\\mathds{P}",
    "󱬌": "\\mathds{Q}",
    "󱬍": "\\mathds{R}",
    "󱬎": "\\mathds{S}",
    "󱬏": "\\mathds{T}",
    "󱬐": "\\mathds{U}",
    "󱬑": "\\mathds{V}",
    "󱬒": "\\mathds{W}",
    "󱬓": "\\mathds{X}",
    "󱬔": "\\mathds{Y}",
    "󱬕": "\\mathds{Z}",
    "󱹷": "\\mathcal{a}",
    "󱹸": "\\mathcal{b}",
    "󱹹": "\\mathcal{c}",
    "󱹺": "\\mathcal{d}",
    "󱹻": "\\mathcal{e}",
    "󱹼": "\\mathcal{f}",
    "󱹽": "\\mathcal{g}",
    "󱹾": "\\mathcal{h}",
    "󱹿": "i",
    "󱺀": "\\mathcal{j}",
    "󱺁": "\\mathcal{k}",
    "󱺂": "\\mathcal{l}",
    "󱺃": "\\mathcal{m}",
    "󱺄": "\\mathcal{n}",
    "󱺅": "\\mathcal{o}",
    "󱺆": "\\mathcal{p}",
    "󱺇": "\\mathcal{q}",
    "󱺈": "\\mathcal{r}",
    "󱺉": "\\mathcal{s}",
    "󱺊": "\\mathcal{t}",
    "󱺋": "\\mathcal{u}",
    "󱺌": "\\mathcal{v}",
    "󱺍": "\\mathcal{w}",
    "󱺎": "\\mathcal{x}",
    "󱺏": "\\mathcal{y}",
    "󱺐": "\\mathcal{z}",
    "󱹝": "\\mathcal{A}",
    "󱹞": "\\mathcal{B}",
    "󱹟": "\\mathcal{C}",
    "󱹠": "\\mathcal{D}",
    "󱹡": "\\mathcal{E}",
    "󱹢": "\\mathcal{F}",
    "󱹣": "\\mathcal{G}",
    "󱹤": "\\mathcal{H}",
    "󱹥": "\\mathcal{I}",
    "󱹦": "\\mathcal{J}",
    "󱹧": "\\mathcal{K}",
    "󱹨": "\\mathcal{L}",
    "󱹩": "\\mathcal{M}",
    "󱹪": "\\mathcal{N}",
    "󱹫": "\\mathcal{O}",
    "󱹬": "\\mathcal{P}",
    "󱹭": "\\mathcal{Q}",
    "󱹮": "\\mathcal{R}",
    "󱹯": "\\mathcal{S}",
    "󱹰": "\\mathcal{T}",
    "󱹱": "\\mathcal{U}",
    "󱹲": "\\mathcal{V}",
    "󱹳": "\\mathcal{W}",
    "󱹴": "\\mathcal{X}",
    "󱹵": "\\mathcal{Y}",
    "󱹶": "\\mathcal{Z}",
    "󱰫": "\\mathfrak{a}",
    "󱰬": "\\mathfrak{b}",
    "󱰭": "\\mathfrak{c}",
    "󱰮": "\\mathfrak{d}",
    "󱰯": "\\mathfrak{e}",
    "󱰰": "\\mathfrak{f}",
    "󱰱": "\\mathfrak{g}",
    "󱰲": "\\mathfrak{h}",
    "󱰳": "\\mathfrak{i}",
    "󱰴": "\\mathfrak{j}",
    "󱰵": "\\mathfrak{k}",
    "󱰶": "\\mathfrak{l}",
    "󱰷": "\\mathfrak{m}",
    "󱰸": "\\mathfrak{n}",
    "󱰹": "\\mathfrak{o}",
    "󱰺": "\\mathfrak{p}",
    "󱰻": "\\mathfrak{q}",
    "󱰼": "\\mathfrak{r}",
    "󱰽": "\\mathfrak{s}",
    "󱰾": "\\mathfrak{t}",
    "󱰿": "\\mathfrak{u}",
    "󱱀": "\\mathfrak{v}",
    "󱱁": "\\mathfrak{w}",
    "󱱂": "\\mathfrak{x}",
    "󱱃": "\\mathfrak{y}",
    "󱱄": "\\mathfrak{z}",
    "󱱅": "\\mathfrak{A}",
    "󱱆": "\\mathfrak{B}",
    "󱱇": "\\mathfrak{C}",
    "󱱈": "\\mathfrak{D}",
    "󱱉": "\\mathfrak{E}",
    "󱱊": "\\mathfrak{F}",
    "󱱋": "\\mathfrak{G}",
    "󱱌": "\\mathfrak{H}",
    "󱱍": "\\mathfrak{I}",
    "󱱎": "\\mathfrak{J}",
    "󱱏": "\\mathfrak{K}",
    "󱱐": "\\mathfrak{L}",
    "󱱑": "\\mathfrak{M}",
    "󱱒": "\\mathfrak{N}",
    "󱱓": "\\mathfrak{O}",
    "󱱔": "\\mathfrak{P}",
    "󱱕": "\\mathfrak{Q}",
    "󱱖": "\\mathfrak{R}",
    "󱱗": "\\mathfrak{S}",
    "󱱘": "\\mathfrak{T}",
    "󱱙": "\\mathfrak{U}",
    "󱱚": "\\mathfrak{V}",
    "󱱛": "\\mathfrak{W}",
    "󱱜": "\\mathfrak{X}",
    "󱱝": "\\mathfrak{Y}",
    "󱱞": "\\mathfrak{Z}",
    "ₔ": "\\textschwa ",
    "󱲥": "\\alpha ",
    "ᵦ": "\\beta ",
    "󱲧": "\\gamma ",
    "󱲨": "\\delta ",
    "󱲩": "\\varepsilon ",
    "󱲪": "\\zeta ",
    "󱲫": "\\eta ",
    "󱲬": "\\theta ",
    "󱲮": "\\iota ",
    "󱲯": "\\kappa ",
    "󱲰": "\\lambda ",
    "󱲱": "\\mu ",
    "󱲲": "\\nu ",
    "󱲳": "\\xi ",
    "󱻹": "\\omicron ",
    "󱲴": "\\pi ",
    "ᵨ": "\\rho ",
    "ᓂ": "\\sigma ",
    "󱲸": "\\tau ",
    "󱲹": "\\upsilon ",
    "ᵩ": "\\varphi ",
    "󱲿": "\\phi ",
    "ᵪ": "\\chi ",
    "󱲼": "\\psi ",
    "󱳀": "\\Gamma ",
    "󱳁": "\\Delta ",
    "󱳂": "\\nabla ",
    "󱳃": "\\Theta ",
    "󱻲": "\\Lambda ",
    "󱳄": "\\Xi ",
    "󱳅": "\\Prod ",
    "󱳆": "\\Sum ",
    "󱳇": "\\Phi ",
    "󱳈": "\\Psi ",
    "؎": "\\infty ",
    "󲓯": "\\infty ",
    "󲒿": "\\to ",
    "󱵦": "\\max ",
    "󱵧": "\\min ",
    "󰄎": ", ",
    "󲓦": "\\times ",
    "󲏑": "_i", #to change
    "󲏒": "^i", #to change
    "󲏏": "_n", #to change
    "󲏐": "^n", #to change
    "󲏕": "_k", #to change
    "󲏖": "^k", #to change
    "⁰": "0",
    "󲏋": "_0", #to change
    "󲏌": "^0", #to change
    "¹": "1",
    "󲏍": "_1", #to change
    "󲏎": "^1", #to change
    "󲏊": "\\text{¶}",
    "󲅯": "\\neq ",
    "󲎨": "/",
    "󲎣": "|",
    "²": "2",
    "³": "3",
    "⁴": "4",
    "⁵": "5",
    "⁶": "6",
    "⁷": "7",
    "⁸": "8",
    "⁹": "9",
    "󲎂": "\\frac{0}{3}",
    "󲍷": "\\frac{1}{2}",
    "󲍸": "\\frac{1}{3}",
    "󲍹": "\\frac{1}{4}",
    "󲍺": "\\frac{1}{5}",
    "󲍻": "\\frac{1}{6}",
    "󲍼": "\\frac{1}{7}",
    "󲍽": "\\frac{1}{8}",
    "󲍾": "\\frac{1}{9}",
    "󲍿": "\\frac{1}{10}",
    "󲎀": "\\frac{2}{3}",
    "󲎁": "\\frac{2}{5}",
    "󲎃": "\\frac{3}{4}",
    "󲎄": "\\frac{3}{5}",
    "󲎅": "\\frac{3}{8}",
    "󲎆": "\\frac{4}{5}",
    "󲎇": "\\frac{5}{6}",
    "󲎈": "\\frac{5}{8}",
    "󲎉": "\\frac{7}{8}",
    "⁻": "-",
    "⁺": "+",
    "ᐟ": "/",
    "⁼": "=",
    "ᵜ": "\\pi ",
    "ᔥ": "\\infty ",
    "󲗹": "\\infty ",
    "ᶿ": "\\theta ",
    "ᚆ": "\\perp",
    "ᵃ": "a",
    "ᵇ": "b",
    "ᶜ": "c",
    "ᵈ": "d",
    "ᵉ": "e",
    "ᶠ": "f",
    "ᵍ": "g",
    "ʰ": "h",
    "ⁱ": "i",
    "ᶨ": "j",
    "ᵏ": "k",
    "ˡ": "l",
    "ᵐ": "m",
    "ⁿ": "n",
    "ᵒ": "o",
    "ᵖ": "p",
    "": "q",
    "𐞥": "q",
    "ʳ": "r",
    "ˢ": "s",
    "ᵗ": "t",
    "ᵘ": "u",
    "ᵛ": "v",
    "ʷ": "w",
    "ˣ": "x",
    "ʸ": "y",
    "ᶻ": "z",
    "ꜝ": "!",
    "ᴬ": "A",
    "ᴮ": "B",
    "󰀂": "C",
    "ᴰ": "D",
    "ᴱ": "E",
    "󰀅": "F",
    "ᴳ": "G",
    "ᴴ": "H",
    "ᴵ": "I",
    "ᴶ": "J",
    "ᴷ": "K",
    "ᴸ": "L",
    "ᴹ": "M",
    "ᴺ": "N",
    "ᴼ": "O",
    "ᴾ": "P",
    "󰀐": "Q",
    "ᴿ": "R",
    "󰀒": "S",
    "ᵀ": "T",
    "ᵁ": "U",
    "ⱽ": "V",
    "ᵂ": "W",
    "󰀗": "X",
    "󰀘": "Y",
    "󰀙": "Z",
    "󱽯": "\\mathds{0}",
    "󱽰": "\\mathds{1}",
    "󱽱": "\\mathds{2}",
    "󱽲": "\\mathds{3}",
    "󱽳": "\\mathds{4}",
    "󱽴": "\\mathds{5}",
    "󱽵": "\\mathds{6}",
    "󱽶": "\\mathds{7}",
    "󱽷": "\\mathds{8}",
    "󱽸": "\\mathds{9}",
    "󱾓": "\\mathds{a}",
    "󱾔": "\\mathds{b}",
    "󱾕": "\\mathds{c}",
    "󱾖": "\\mathds{d}",
    "󱾗": "\\mathds{e}",
    "󱾘": "\\mathds{f}",
    "󱾙": "\\mathds{g}",
    "󱾚": "\\mathds{h}",
    "󱾛": "\\mathds{i}",
    "󱾜": "\\mathds{j}",
    "󱾝": "\\mathds{k}",
    "󱾞": "\\mathds{l}",
    "󱾟": "\\mathds{m}",
    "󱾠": "\\mathds{n}",
    "󱾡": "\\mathds{o}",
    "󱾢": "\\mathds{p}",
    "󱾣": "\\mathds{q}",
    "󱾤": "\\mathds{r}",
    "󱾥": "\\mathds{s}",
    "󱾦": "\\mathds{t}",
    "󱾧": "\\mathds{u}",
    "󱾨": "\\mathds{v}",
    "󱾩": "\\mathds{w}",
    "󱾪": "\\mathds{x}",
    "󱾫": "\\mathds{y}",
    "󱾬": "\\mathds{z}",
    "󱽹": "\\mathds{A}",
    "󱽺": "\\mathds{B}",
    "󱽻": "\\mathds{C}",
    "󱽼": "\\mathds{D}",
    "󱽽": "\\mathds{E}",
    "󱽾": "\\mathds{F}",
    "󱽿": "\\mathds{G}",
    "󱾀": "\\mathds{H}",
    "󱾁": "\\mathds{I}",
    "󱾂": "\\mathds{J}",
    "󱾃": "\\mathds{K}",
    "󱾄": "\\mathds{L}",
    "󱾅": "\\mathds{M}",
    "󱾆": "\\mathds{N}",
    "󱾇": "\\mathds{O}",
    "󱾈": "\\mathds{P}",
    "󱾉": "\\mathds{Q}",
    "󱾊": "\\mathds{R}",
    "󱾋": "\\mathds{S}",
    "󱾌": "\\mathds{T}",
    "󱾍": "\\mathds{U}",
    "󱾎": "\\mathds{V}",
    "󱾏": "\\mathds{W}",
    "󱾐": "\\mathds{X}",
    "󱾑": "\\mathds{Y}",
    "󱾒": "\\mathds{Z}",
    "󲋴": "\\mathcal{a}",
    "󲋵": "\\mathcal{b}",
    "󲋶": "\\mathcal{c}",
    "󲋷": "\\mathcal{d}",
    "󲋸": "\\mathcal{e}",
    "󲋹": "\\mathcal{f}",
    "󲋺": "\\mathcal{g}",
    "󲋻": "\\mathcal{h}",
    "󲋼": "i",
    "󲋽": "\\mathcal{j}",
    "󲋾": "\\mathcal{k}",
    "󲋿": "\\mathcal{l}",
    "󲌀": "\\mathcal{m}",
    "󲌁": "\\mathcal{n}",
    "󲌂": "\\mathcal{o}",
    "󲌃": "\\mathcal{p}",
    "󲌄": "\\mathcal{q}",
    "󲌅": "\\mathcal{r}",
    "󲌆": "\\mathcal{s}",
    "󲌇": "\\mathcal{t}",
    "󲌈": "\\mathcal{u}",
    "󲌉": "\\mathcal{v}",
    "󲌊": "\\mathcal{w}",
    "󲌋": "\\mathcal{x}",
    "󲌌": "\\mathcal{y}",
    "󲌍": "\\mathcal{z}",
    "󲋚": "\\mathcal{A}",
    "󲋛": "\\mathcal{B}",
    "󲋜": "\\mathcal{C}",
    "󲋝": "\\mathcal{D}",
    "󲋞": "\\mathcal{E}",
    "󲋟": "\\mathcal{F}",
    "󲋠": "\\mathcal{G}",
    "󲋡": "\\mathcal{H}",
    "󲋢": "\\mathcal{I}",
    "󲋣": "\\mathcal{J}",
    "󲋤": "\\mathcal{K}",
    "󲋥": "\\mathcal{L}",
    "󲋦": "\\mathcal{M}",
    "󲋧": "\\mathcal{N}",
    "󲋨": "\\mathcal{O}",
    "󲋩": "\\mathcal{P}",
    "󲋪": "\\mathcal{Q}",
    "󲋫": "\\mathcal{R}",
    "󲋬": "\\mathcal{S}",
    "󲋭": "\\mathcal{T}",
    "󲋮": "\\mathcal{U}",
    "󲋯": "\\mathcal{V}",
    "󲋰": "\\mathcal{W}",
    "󲋱": "\\mathcal{X}",
    "󲋲": "\\mathcal{Y}",
    "󲋳": "\\mathcal{Z}",
    "󲋴": "\\mathfrak{a}",
    "󲂩": "\\mathfrak{b}",
    "󲂪": "\\mathfrak{c}",
    "󲂫": "\\mathfrak{d}",
    "󲂬": "\\mathfrak{e}",
    "󲂭": "\\mathfrak{f}",
    "󲂮": "\\mathfrak{g}",
    "󲂯": "\\mathfrak{h}",
    "󲂰": "\\mathfrak{i}",
    "󲂱": "\\mathfrak{j}",
    "󲂲": "\\mathfrak{k}",
    "󲂳": "\\mathfrak{l}",
    "󲂴": "\\mathfrak{m}",
    "󲂵": "\\mathfrak{n}",
    "󲂶": "\\mathfrak{o}",
    "󲂷": "\\mathfrak{p}",
    "󲂸": "\\mathfrak{q}",
    "󲂹": "\\mathfrak{r}",
    "󲂺": "\\mathfrak{s}",
    "󲂻": "\\mathfrak{t}",
    "󲂼": "\\mathfrak{u}",
    "󲂽": "\\mathfrak{v}",
    "󲂾": "\\mathfrak{w}",
    "󲂿": "\\mathfrak{x}",
    "󲃀": "\\mathfrak{y}",
    "󲃁": "\\mathfrak{z}",
    "󲃂": "\\mathfrak{A}",
    "󲃃": "\\mathfrak{B}",
    "󲃄": "\\mathfrak{C}",
    "󲃅": "\\mathfrak{D}",
    "󲃆": "\\mathfrak{E}",
    "󲃇": "\\mathfrak{F}",
    "󲃈": "\\mathfrak{G}",
    "󲃉": "\\mathfrak{H}",
    "󲃊": "\\mathfrak{I}",
    "󲃋": "\\mathfrak{J}",
    "󲃌": "\\mathfrak{K}",
    "󲃍": "\\mathfrak{L}",
    "󲃎": "\\mathfrak{M}",
    "󲃏": "\\mathfrak{N}",
    "󲃐": "\\mathfrak{O}",
    "󲃑": "\\mathfrak{P}",
    "󲃒": "\\mathfrak{Q}",
    "󲃓": "\\mathfrak{R}",
    "󲃔": "\\mathfrak{S}",
    "󲃕": "\\mathfrak{T}",
    "󲃖": "\\mathfrak{U}",
    "󲃗": "\\mathfrak{V}",
    "󲃘": "\\mathfrak{W}",
    "󲃙": "\\mathfrak{X}",
    "󲃚": "\\mathfrak{Y}",
    "󲃛": "\\mathfrak{Z}",
    "ᵅ": "\\alpha ",
    "ᵝ": "\\beta ",
    "ᵞ": "\\gamma ",
    "ᵟ": "\\delta ",
    "ᵋ": "\\varepsilon ",
    "󲄧": "\\zeta ",
    "ᵑ": "\\eta ",
    "󲄩": "\\theta ",
    "󲄫": "\\iota ",
    "󲄬": "\\kappa ",
    "󲄭": "\\lambda ",
    "󲄮": "\\mu ",
    "󲄯": "\\nu ",
    "󲄰": "\\xi ",
    "󲍶": "\\omicron ",
    "󲄱": "\\pi ",
    "󲄲": "\\rho ",
    "󲄴": "\\sigma ",
    "󲄵": "\\tau ",
    "󲄶": "\\upsilon ",
    "ᵠ": "\\varphi",
    "𝇉": "\\phi ",
    "󲄼": "\\phi ",
    "ᵡ": "\\chi ",
    "󲄹": "\\psi ",
    "󲄽": "\\Gamma ",
    "󲄾": "\\Delta ",
    "󲄿": "\\nabla ",
    "󲅀": "\\Theta ",
    "󲍯": "\\Lambda ",
    "󲅁": "\\Xi ",
    "󲅂": "\\Prod ",
    "󲅃": "\\Sum ",
    "󲅄": "\\Phi ",
    "󲅅": "\\Psi ",
    "˟": "\\times ",
    "ᢁ": "\\infty ",
    "󲗉": "\\to ",
    "󲇣": "\\max ",
    "󲇤": "\\min ",
    "󰁱": ", ",
    "󲗰": "\\times ",
    "⁽": "(",
    "⁾": ")",
    "₍": "(",
    "₎": ")",
    "󲎔": "(",
    "󲎕": ")",
    "󱼗": "(",
    "󱼘": ")",
    "⹀": "=",
    "ũ": "\\tilde u",
    "⥠": "\\mathbf{1}",
    "ꖾ": "\\operatorname{Hom}",
    "▢": "\\operatorname{Obj}",
    "🝱": "\\operatorname{GL}",
    "🝕": "\\operatorname{SL}",
    "㏿": "\\operatorname{Gal}",
    "﹪": "\\mod ",
    "⨄": "\\operatorname{lcm}",
    "⩀": "\\gcd ",
    "ɐ": "\\arrow ",
    "⬏": "bend left",
    "⬎": "bend right",
    "☺": "\\smiley ",
    "⇔": "\\Leftrightarrow ",
    "⇒": "\\Rightarrow ",
    "⇐": "\\Leftarrow ",
    "∞": "\\infty ",
    "𝄽": "\\operatorname{id}",
    "∂": "\\partial ",
    "⫚": "\\choose ",
    "√": "\\sqrt",
    "∛": "\\sqrt[3]{",
    "∜": "\\sqrt[4]{",
    "⌝": "}",
    "⸣": "}",
    "⨃": "\\mathbin{\\dot{\\cup}}",
    "∪": "\\cup ",
    "∩": "\\cap ",
    "⨃": "\\mathop{\\dot{\\bigcup}}",
    "⋃": "\\bigcup ",
    "⋂": "\\bigcap ",
    "⊃": "\\supset ",
    "⊂": "\\subset ",
    "⊄": "\\not\\subset ",
    "⊈": "\\nsubseteq ",
    "⊆": "\\subseteq ",
    "⊊": "\\subsetneq ",
    "⊗": "\\otimes ",
    "⊕": "\\oplus ",
    "⊖": "\\ominus ",
    "⨯": "\\times ",
    "∘": "\\circ ",
    "±": "\\pm ",
    "∓": "\\mp ",
    "~": "\\sim ",
    "≈": "\\approx ",
    "≅": "\\cong ",
    "Σ": "\\sum ",
    "≔": "=",
    "⋅": "\\cdot ",
    "·": "\\cdot ",
    "⸳": "\\cdot ",
    "⠤": "\\cdots ",
    "…": "\\cdots ",
    "⋯": "\\cdots ",
    "⋱": "\\ddots ",
    "⋰": "\\iddots ",
    "⋮": "\\vdots ",
    "⤉": "\\max ",
    "⤈": "\\min ",
    "¬": "\\neg ",
    "∈": "\\in ",
    "∋": "\\ni ",
    "∉": "\\notin ",
    "≤": "\\leq ",
    "⪗": "\\nleq ",
    "≥": "\\geq ",
    "⪘": "\\ngeq ",
    "′": "'",
    "″": "''",
    "”": "''",
    "‴": "'''",
    "⁗": "''''",
    "≡": "\\equiv ",
    "≠": "\\neq ",
    "∅": "\\emptyset ",
    "Ø": "\\emptyset ",
    "⮂": "\\rightleftarrows ",
    "↦": "\\mapsto ",
    "⟼": "\\mapsto ",
    "→": "\\to ",
    "∀": "\\forall ",
    "ž": "{\\overline{z}}",
    "⁒": "\\frac ",
    "╱": "}{",
    "‗": "{\\underline{",
    "¯": "\\overline ",
    "ㇸ": "{\\widehat{",
    "﹋": "{\\overrightarrow{",
    "„": "}}",
    "❴": "\\left\\{",
    "❵": "\\right\\}",
    "⌊": "\\left\\lfloor ",
    "⌋": "\\right\\rfloor ",
    "⌈": "\\left\\lceil ",
    "⌉": "\\right\\rceil ",
    # "(": "\\left(",
    # ")": "\\right)",
    "【": "\\left(",
    "】": "\\right)",
    "⦋": "\\left[",
    "⦌": "\\right]",
    "⦃": "\\left\\{\\begin{matrix}",
    "⦄": "\\end{matrix}\\right\\}",
    "⟦": "\\left[\\begin{matrix}",
    "⟧": "\\end{matrix}\\right]",
    "⟬": "\\langle\\begin{matrix}",
    "⟭": "\\end{matrix}\\rangle",
    "⦅": "\\left(\\begin{matrix}",
    "⦆": "\\end{matrix}\\right)",
    "⁑": "\\end{matrix}\\right.",
    "⢨": "\\left.",
    "⡅": "\\right.",
    "⸢": "\\text{",
    "⸥": "}",
    "⌜": "\\text{",
    "⌟": "}",
    "ѵ": "\\vee",
    "Ѵ": "\\Vee",
    "⇁": "harpoon",
    "⦙": "dotted",
    "¦": "dashed",
    "⟝": "maps to",
    "⤚": "tail",
    "⤳": "shift right=",
    "⬿": "shift left=",
    "ǂ": " description",
    "↓": "'",
    "⪼": "two heads",
    "⟨": "\\langle ",
    "⟩": "\\rangle ",
    "∫": "\\int ",
    "∬": "\\iint ",
    "∭": "\\iiint ",
    "⨌": "\\iiiint ",
    "∮": "\\oint ",
    "🢔": "\\left(",
    "🢖": "\\right)^T",
    "⫾": "|",
    "⥏": "\\left|",
    "⥑": "\\right|",
    "☃": "{\\text{\\raisebox{-3px}{\\scsnowman[scale=1.5,body,hat=red,muffler=blue]}}}",
    "󲅾": "*",
    "": "^*",
    "∗": "^*", #deprecate
    "󷹁": "^{-1}",
    "󲗿": "\\ln ",
    "󲘀": "\\lg ",
    "󲘁": "\\operatorname{tr}",
    "󲘂": "\\operatorname{SL}",
    "󲘃": "\\operatorname{GL}",
    "󲘄": "\\operatorname{rk}",
    "󲘇": "\\operatorname{End}",
    "󲘈": "\\operatorname{Aut}",
    "󲘉": "\\operatorname{Gal}",
    "󲘊": "\\operatorname{ker}",
    "󲘋": "\\log ",
    "󲘌": "\\sin ",
    "󲘍": "\\cos ",
    "󲘎": "\\tan ",
    "󲘏": "\\sec ",
    "󲘐": "\\csc ",
    "󲘑": "\\cot ",
    "󲘒": "\\operatorname{Ass}",
    "󲘓": "\\operatorname{arg}",
    "󲘔": "\\max ",
    "󲘕": "\\min ",
    "󲘖": "\\exp ",
    "󲘗": "\\operatorname{ln}",
    "󲘘": "\\det ",
    "󲘙": "\\deg ",
    "󲘚": "\\operatorname{erf}",
    "󲘛": "\\operatorname{int}",
    "󲘜": "\\gcd ",
    "󲘝": "\\operatorname{lcm}",
    "󲘞": "\\operatorname{hom}",
    "󲘟": "\\operatorname{obj}",
    "󲘠": "\\lim ",
    "󲘡": "\\inf ",
    "󲘢": "\\sup ",
    "󲘣": "\\mod ",
    "󲘤": "\\operatorname{PGL}",
    "󲘥": "\\operatorname{PSL}",
    "󲘦": "\\operatorname{sgn}",
    "󲘧": "\\operatorname{tor}",
    "󲘫": "\\operatorname{var}",
    "󲘬": "\\operatorname{std}",
    "󲘭": "\\operatorname{cov}",
    "󲘮": "\\operatorname{Spec}",
    "󲘯": "\\sinh ",
    "󲘰": "\\cosh ",
    "󲘱": "\\tanh ",
    "󲘲": "\\operatorname{sech}",
    "󲘳": "\\operatorname{csch}",
    "󲘴": "\\operatorname{coth}",
    "󲘵": "\\operatorname{char}",
    "󲘶": "\\operatorname{curl}",
    "󲘷": "\\operatorname{frob}",
    "󲘸": "\\operatorname{grad}",
    "󲘹": "\\operatorname{rank}",
    "󲘺": "\\operatorname{span}",
    "󲘼": "\\operatorname{erfc}",
    "󲘽": "\\operatorname{MEME}",
    "󲘾": "\\operatorname{null}",
    "󲘿": "\\operatorname{VOID}",
    "󲙀": "\\operatorname{corr}",
    "⌗": "\\# ",
    "∤": "\\nmid ",
    "¶": "\\text{¶}",
    "⋄": "\\diamond ",
    "♢": "\\diamondsuit ",
    "∖": "\\setminus ",
    "↑": "\\uparrow ",
    "↓": "\\downarrow ",
    "⊲": "\\trianglelefteq ",
    "𝍱": "\\frac{1}{2}\\pi ",
    "˜": "\\tilde ",
    "󲗦": "\\cdot "
}
subs = "ₐₑₕᵢⱼₖₗₘₙ󰂼ₚᵣₛₜᵤᵥₓ󰂓󰂔󰂕󰂖󰂗󰂘󰂙󰂚󰂛󰂜󰂝󰂞󰂟󰂠󰂡󰂢󰂣󰂤󰂥󰂦󰂧󰂨󰂩󰂪󰂫󰂬󱰫󱰬󱰭󱰮󱰯󱰰󱰱󱰲󱰳󱰴󱰵󱰶󱰷󱰸󱰹󱰺󱰻󱰼󱰽󱰾󱰿󱱀󱱁󱱂󱱃󱱄󱱅󱱆󱱇󱱈󱱉󱱊󱱋󱱌󱱍󱱎󱱏󱱐󱱑󱱒󱱓󱱔󱱕󱱖󱱗󱱘󱱙󱱚󱱛󱱜󱱝󱱞󱹷󱹸󱹹󱹺󱹻󱹼󱹽󱹾󱹿󱺀󱺁󱺂󱺃󱺄󱺅󱺆󱺇󱺈󱺉󱺊󱺋󱺌󱺍󱺎󱺏󱺐󱹝󱹞󱹟󱹠󱹡󱹢󱹣󱹤󱹥󱹦󱹧󱹨󱹩󱹪󱹫󱹬󱹭󱹮󱹯󱹰󱹱󱹲󱹳󱹴󱹵󱹶󱬖󱬗󱬘󱬙󱬚󱬛󱬜󱬝󱬞󱬟󱬠󱬡󱬢󱬣󱬤󱬥󱬦󱬧󱬨󱬩󱬪󱬫󱬬󱬭󱬮󱬯󱫼󱫽󱫾󱫿󱬀󱬁󱬂󱬃󱬄󱬅󱬆󱬇󱬈󱬉󱬊󱬋󱬌󱬍󱬎󱬏󱬐󱬑󱬒󱬓󱬔󱬕󱷾󱷿󱸀󱸁󱸂󱸃󱸄󱸆󱸇󱸈󱸉󱸊󱸋󱸌󱸍󱸎󱸏󱸐󱸑󱸒󱸓󱸔󱸕󱸖󱸗󱷤󱷥󱷦󱷧󱷨󱷩󱷪󱷫󱷬󱷭󱷮󱷯󱷰󱷱󱷲󱷳󱷴󱷵󱷶󱷷󱷸󱷹󱷺󱷻󱷼󱷽₀₁₂₃₄₅₆₇₈₉󱫲󱫳󱫴󱫵󱫶󱫷󱫸󱫹󱫺󱫻󱭮󱭯󱭰󱭱󱭲󱭳󱭴󱭵󱭶󱭷󱽎󱽏󱽐󱽑󱽒󱽓󱽔󱽕󱽖󱽘󱽙₊₋󲓦󲓧󲓩󱴁󲓥󲓜󱳺󱳹󱳝󰄏﹕󱼫󱳞󱼬󱼭󱵗₌󱳫󱳬󱳭󱳮󱳯󱳲󱳪󲒨󱳳󱳰󰄟󰄞󱴤󱴧󱴣󱴦󱴥󱴨󱼪󱼦󱳠󱼮󱴉󱴖󱴗󱴘󱴙󱴚󱴬󱴳󱴲󱴱󱴫󱴯󱴮󱴭󱴩󱶵󱴵󱴶󱳗󱼰󱽝󱼲󱼱󱽜󱼳󱴝󱴞󱽢󱽣󱽤󱽥󱽦󱽧󱽨󱽩󱽬󱽟󱽞󱴟󱴠󱴡󱴢󱷉󱳢󱳣󲒿󱵄󱵃󲒾󱵊󱵉󱵈󱵇󲓬󱳤󱵒󱵑󱵐󱵏󱳻󱳼󱳽󱳾󱵍󱵎󱵌󱵋󲓟󱲾󱳡󱼴󱼵󱼶󱼷󱼸󱼹󱼺󱼻󱼾󱼿󱳂󲓨󲓘󲓚󲓗󲓛󲓕󲓖󲓙󲓠󲓡󲓣󱽇󲓯󱲡󱲣₍₎󱼍󱼎󱴹󱴺󱼑󱼒󱼓󱼔󲒕󲒖󱼕󱼖󱲝󱲞󱼏󱼐󲒍󲒎󱼗󱼘󲒓󲒔󱶚󱶛󱼟󱼠󱵜󱵝󱵚󱵛󱼙󱼚󱳜󱼧󱼡󱼢󱳧󱳨󱴑﹖󱴍󲒘󱲥󱲦󱲧󱲨󱲩󱲪󱲫󱲬󱲮󱲯󱲰󱲱󱲲󱲳󱻹󱲴󱼨󱲵󱲷󱲸󱲹󱲺󱲿󱲻󱲼󱲽󱳀󱳁󱳃󱻲󱳄󱳅󱳆󱳇󱳈󱳉󱼅󱻺󱻻󱻼󱻽󱻾󱻿󱼀󱼁󱼂󱼃󱼄󱼆󱼇󱼈󱼉󱼊󱼋󱼌󱵦󱵧󰄎󲓦󱽍"
sups = "ᵃᵇᶜᵈᵉᶠᵍᶢʰⁱʲᶨᵏˡᵐⁿᵒᵖ𐞥ʳˢᵗᵘᵛʷˣʸᶻᴬᴮ󰀂ᴰᴱ󰀅ᴳᴴᵸᴵᴶᴷᴸᴹᴺᴼᴾ󰀐ᴿ󰀒ᵀᵁⱽᵂ󰀗󰀘󰀙󲂨󲂩󲂪󲂫󲂬󲂮󲂯󲂰󲂱󲂲󲂳󲂴󲂵󲂶󲂷󲂸󲂹󲂺󲂻󲂼󲂽󲂾󲂿󲃀󲃁󲃂󲃃󲃄󲃅󲃆󲃇󲃈󲃉󲃊󲃋󲃌󲃍󲃎󲃏󲃐󲃑󲃒󲃓󲃔󲃕󲃖󲃗󲃘󲃙󲃚󲃛󲋴󲋵󲋶󲋷󲋸󲋹󲋺󲋻󲋼󲋽󲋾󲋿󲌀󲌁󲌂󲌃󲌄󲌅󲌆󲌇󲌈󲌉󲌊󲌋󲌌󲌍󲋚󲋛󲋜󲋝󲋞󲋟󲋠󲋡󲋢󲋣󲋤󲋥󲋦󲋧󲋨󲋩󲋪󲋫󲋬󲋭󲋮󲋯󲋰󲋱󲋲󲋳󱾓󱾔󱾕󱾖󱾗󱾘󱾙󱾚󱾛󱾜󱾝󱾞󱾟󱾠󱾡󱾢󱾣󱾤󱾥󱾦󱾧󱾨󱾩󱾪󱾫󱾬󱽹󱽺󱽻󱽼󱽽󱽾󱽿󱾀󱾁󱾂󱾃󱾄󱾅󱾆󱾇󱾈󱾉󱾊󱾋󱾌󱾍󱾎󱾏󱾐󱾑󱾒󲉻󲉼󲉽󲉾󲉿󲊀󲊁󲊂󲊃󲊄󲊅󲊆󲊇󲊈󲊉󲊊󲊋󲊌󲊍󲊎󲊏󲊐󲊑󲊒󲊓󲊔󲉡󲉢󲉣󲉤󲉥󲉦󲉧󲉨󲉩󲉪󲉫󲉬󲉭󲉮󲉯󲉰󲉱󲉲󲉳󲉴󲉵󲉶󲉷󲉸󲉹󲉺⁰¹²³⁴⁵⁶⁷⁸⁹󱽯󱽰󱽱󱽲󱽳󱽴󱽵󱽶󱽷󱽸󱿫󱿬󱿭󱿮󱿯󱿰󱿱󱿲󱿳󱿴󲏌󲏋󲏎󲏍󲏐󲏏󲏒󲏑󲏓󲏖󲏕⁺⁻˟󲗰󲗱󲗳󲅾󲗯󲗦󲅷󲅶󲅚󰁲ᐟ󲎨󲅛󲎩󲎪󲇔⁼󲅨󲅩󲅪󲅫󲅬󲅯󲅧󲖲󲅰󲅭󰂂󰂁󲆡󲆤󲆠󲆣󲆢󲆥󲎧󲎣󲅝󲎫󲆇󲆓󲆔󲆕󲆖󲆗󲆩󲆰󲆯󲆮󲆨󲆬󲆫󲆪󲆦󲈲󲆲󲆳󲅔󲎭󲏚󲎯󲎮󲏙󲎰󲆚󲆛󲏟󲏠󲏡󲏢󲏣󲏤󲏥󲏦󲏩󲏜󲏛󲆜󲆝󲆞󲆟󲉆󲅟󲅠󲗉󲇁󲇀󲗈󲇇󲇆󲇅󲇄󲗶󲅡󲇏󲇎󲇍⸆󲇌ᚆꜛꜜ󲅸󲅹󲅺󲅻󲇊󲇋󲇈󲇉󲗩󲄻󲅞󲎱󲎲󲎳󲎴󲎵󲎶󲎸󲎷󲎻󲎼󲄿󲗲󲗢󲗤󲗡󲗥󲗟󲗠󲗣󲗪󲗫󲗭󲏄󲗹ᔥ󲄞󲄠⁽⁾󲎊󲎋󲆶󲆷󲎎󲎏󲎐󲎑󲖟󲖠󲎒󲎓󲄚󲄛󲎌󲎍󲖗󲖘󲎔󲎕󲖝󲖞󲈗󲈘󲎜󲎝󲇙󲇚󲇗󲇘󲎖󲎗󲅙󲎤󲎞󲎟󲅤󲅥󲆎ꜝ󲆊󲖢ᵅ󲄢ᵝᵞᵟᵋ󲄧ᵑ󲄨ᶿ󲄫󲄬󲄭󲄮󲄯󲄰󲍶󲄱󲎥ᵜ󲄲󲄷ᵠ󲄼𝇉ᵡ󲄸󲄹󲄺󲄽󲄾󲅀󲍯󲅁󲅂󲅃󲅄󲅅󲅆ᶛᶝᶞᶟᶡ󲎂󲍷󲍸󲍹󲍺󲍻󲍼󲍽󲍾󲎀󲎁󲎃󲎄󲎅󲎆󲎇󲎈󲎉󲇣󲇤󰁱󲗰󲏊"
#missing friends: ﹖﹕ꜝ
#bruuu my computer garbage my left alt key is stuck and i have to type in vscode and mouse copy pasta into discord 😞😕☹😞 𝕎𝓗𝐘 𝓦𝐇𝕐